# .github/workflows/ci.yml  (only the relevant parts shown)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Enable Buildx (needed for the cache backend)
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3   # <-- new step

      # 2. Build the image **with caching** and load it locally
      - name: Build (cache layers)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: movies-api:${{ github.sha }}
          load: true                       # we only need the image locally
          cache-from: type=gha,scope=movies-api
          cache-to: type=gha,mode=max,scope=movies-api

      # 3. Start container, install test deps, run test.py … (unchanged)
      - name: Start container
        run: |
          docker run -d \
            --name movies-api \
            -p 1993:605 \
            movies-api:${{ github.sha }}
          sleep 5
      - name: Install test deps
        run: |
          docker exec movies-api \
            python -m pip install --no-cache-dir requests python-dotenv
      - name: Run tests
        run: |
          docker exec -e URL="http://localhost:605/movie" \
            movies-api python /app/test.py
